### ISSUE TITLE
사이드 바 마이페이지 클릭 시 닫히게 설정 및 로그인, 회원가입 버튼 로직 수정

### ISSUE THREAD

**Issue by yangjaehyuk** [YBE-7/MiniProject_FE#115]
## Description
사이드 바 마이페이지 클릭 시 닫히게 설정 및 로그인, 회원가입 버튼 로직 수정

## Todo

- [x] 사이드 바 로직 수정
- [x] 로그인 버튼 로직 수정
- [x] 회원가입 버튼 로직 수정

## ETC
