### ISSUE TITLE
달력 모달 연결 & react query + axios 연결 준비

### ISSUE THREAD

**Issue by skyeome** [YBE-7/MiniProject_FE#36]
## Description
지민님이 만들어주신 달력모달을 페이지에 연결하고, 
react query를 사용하기 위한 준비작업을 진행합니다.

## Todo

- [x] 달력모달 컴포넌트를 지역별 상품 페이지에 삽입
- [x] React Query 설치 및 기본 설정
- [x] 기존 상수 데이터를 가짜로 네트워크를 통해 받아오는것처럼 변경 (0.1초후 Promise로 반환)

## ETC
react-query, axios 라이브러리를 설치해야 할것같습니다.
