### ISSUE TITLE
상품 상세 페이지 디자인 추가

### ISSUE THREAD

**Issue by moana16** [YBE-7/MiniProject_FE#37]
## Description

상품 상세 페이지 디자인 추가 하겠습니다

## Todo

- [x] 이미지 캐러셀 추가
- [x] 객실 상품 몇개 남았는지 문구 추가
- [x] 달력 모달 이미지 변경 및 인원 수 모달 추가
