### ISSUE TITLE
상품 상세 페이지, 객실 정보 API 연결 초기 작업

### ISSUE THREAD

**Issue by moana16** [YBE-7/MiniProject_FE#39]
## Description

API로 받아올 데이터들 타입 지정하고 코드 내에서 동작하도록 기본 세팅 할 예정입니다
## Todo

- [x] response data 타입설정
- [x] API 명세서대로 axios 연결 추가
- [x] data에 맞는 코드 수정
