### ISSUE TITLE
상품목록용 스켈레톤 컴포넌트 생성

### ISSUE THREAD

**Issue by skyeome** [YBE-7/MiniProject_FE#54]
## Description
상품 목록용 공통 스켈레톤 UI를 생성합니다.

## Todo

- [x] TOP 숙소 Skeleton Component 생성
- [x] 슬라이드 형 Skeleton Component 생성
- [x] 지역별 숙소 Skeleton Component 생성
