### ISSUE TITLE
무한스크롤시 스켈레톤 UI 노출

### ISSUE THREAD

**Issue by skyeome** [YBE-7/MiniProject_FE#61]
## Description
현재는 초기 로드시에만 스켈레톤 UI가 노출되고
무한스크롤시 스켈레톤 UI가 노출이 되지 않아서 이를 해결하려고 합니다.

## Todo

- [x] 무한 스크롤시 아래에 skeleton ui 노출
- [x] 필터링 코드 리팩토링
- [x] ErrorBoundary 코드 리팩토링
